import '../services/api_service.dart';
import '../services/database_service.dart';
import '../services/sync_service.dart';
import '../models/base_model.dart';
import 'package:gems_core/gems_core.dart';
import 'dart:convert';

/// Base Repository - Works with Freezed models
/// T must have toJson() and fromJson() (generated by Freezed)
abstract class BaseRepository<T extends BaseModel> {
  final ApiService apiService;
  final DatabaseService databaseService;
  final SyncService syncService;
  final String baseEndpoint;

  BaseRepository({
    required this.apiService,
    required this.databaseService,
    required this.syncService,
    required this.baseEndpoint,
  });

  /// Parse JSON to model (use Freezed's fromJson)
  T fromJson(Map<String, dynamic> json);

  // Helper methods for cache operations
  String _cacheKey(String suffix) => '${baseEndpoint}_$suffix';
  String get _listCacheKey => _cacheKey('all');
  String _itemCacheKey(String id) => _cacheKey(id);

  // Helper: Get cached list
  List<T>? _getCachedList() {
    final cachedJson = databaseService.get<String>(_listCacheKey);
    if (cachedJson == null) return null;
    try {
      final cached = (jsonDecode(cachedJson) as List)
          .map((e) => fromJson(e as Map<String, dynamic>))
          .toList();
      return cached.isNotEmpty ? cached : null;
    } catch (e) {
      return null;
    }
  }

  // Helper: Get cached item
  T? _getCachedItem(String id) {
    final cachedJson = databaseService.get<String>(_itemCacheKey(id));
    if (cachedJson == null) return null;
    try {
      return fromJson(jsonDecode(cachedJson) as Map<String, dynamic>);
    } catch (e) {
      return null;
    }
  }

  // Helper: Save list to cache
  Future<void> _saveListToCache(List<T> items) async {
    await databaseService.save(
      _listCacheKey,
      jsonEncode(items.map((item) => item.toJson()).toList()),
    );
  }

  // Helper: Save item to cache
  Future<void> _saveItemToCache(String id, T item) async {
    await databaseService.save(_itemCacheKey(id), jsonEncode(item.toJson()));
  }

  // Helper: Invalidate list cache
  Future<void> _invalidateListCache() async {
    await databaseService.delete(_listCacheKey);
  }

  // Helper: Queue sync operation
  Future<void> _queueSync(String method, String endpoint, Map<String, dynamic>? data) async {
    await syncService.addToQueue(SyncItem(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      method: method,
      endpoint: endpoint,
      data: data,
      timestamp: DateTime.now(),
    ));
  }

  /// Get all - Returns Result<T> directly
  Future<Result<List<T>>> getAll({bool useCache = true}) async {
    try {
      // Try cache first
      if (useCache) {
        final cached = _getCachedList();
        if (cached != null) {
          _refreshListInBackground(); // Update cache in background
          return Result.success(cached);
        }
      }

      // Fetch from API
      final response = await apiService.get<List<dynamic>>(
        baseEndpoint,
        fromJson: (data) => (data as List)
            .map((e) => fromJson(e as Map<String, dynamic>))
            .toList(),
      );

      if (response.success && response.data != null) {
        final items = response.data! as List<T>;
        if (useCache) await _saveListToCache(items);
        return Result.success(items);
      }

      // API failed - try cache as fallback
      if (useCache) {
        final cached = _getCachedList();
        if (cached != null) return Result.success(cached);
      }

      return Result.failure(ApiError(message: response.message ?? 'Failed to fetch'));
    } catch (e, stackTrace) {
      return Result.failure(NetworkError.fromException(e, stackTrace));
    }
  }

  /// Background refresh of list cache
  Future<void> _refreshListInBackground() async {
    try {
      final response = await apiService.get<List<dynamic>>(
        baseEndpoint,
        fromJson: (data) => (data as List)
            .map((e) => fromJson(e as Map<String, dynamic>))
            .toList(),
      );
      if (response.success && response.data != null) {
        await _saveListToCache(response.data! as List<T>);
      }
    } catch (e) {
      // Silently fail - we already have cached data
    }
  }

  /// Get by ID - Returns Result<T> directly
  Future<Result<T>> getById(String id, {bool useCache = true}) async {
    try {
      // Try cache first
      if (useCache) {
        final cached = _getCachedItem(id);
        if (cached != null) {
          _refreshItemInBackground(id); // Update cache in background
          return Result.success(cached);
        }
      }

      // Fetch from API
      final response = await apiService.get<Map<String, dynamic>>(
        '$baseEndpoint/$id',
        fromJson: (data) => data as Map<String, dynamic>,
      );

      if (response.success && response.data != null) {
        final item = fromJson(response.data!);
        if (useCache) await _saveItemToCache(id, item);
        return Result.success(item);
      }

      // API failed - try cache as fallback
      if (useCache) {
        final cached = _getCachedItem(id);
        if (cached != null) return Result.success(cached);
      }

      return Result.failure(ApiError(message: response.message ?? 'Failed to fetch'));
    } catch (e, stackTrace) {
      return Result.failure(NetworkError.fromException(e, stackTrace));
    }
  }

  /// Background refresh of item cache
  Future<void> _refreshItemInBackground(String id) async {
    try {
      final response = await apiService.get<Map<String, dynamic>>(
        '$baseEndpoint/$id',
        fromJson: (data) => data as Map<String, dynamic>,
      );
      if (response.success && response.data != null) {
        await _saveItemToCache(id, fromJson(response.data!));
      }
    } catch (e) {
      // Silently fail - we already have cached data
    }
  }

  /// Create - Returns Result<T> directly
  Future<Result<T>> create(T model, {bool syncOffline = true}) async {
    try {
      final response = await apiService.post<Map<String, dynamic>>(
        baseEndpoint,
        data: model.toJson(),
        fromJson: (data) => data as Map<String, dynamic>,
      );

      if (response.success && response.data != null) {
        final item = fromJson(response.data!);
        // Use item.id (from server) or model.id (if server doesn't return id)
        final itemId = item.toJson()['id']?.toString() ?? model.toJson()['id']?.toString();
        if (itemId != null) {
          await _saveItemToCache(itemId, item);
        }
        await _invalidateListCache();
        return Result.success(item);
      }

      // API failed - save locally for offline support
      if (syncOffline) {
        // Always save to cache using model's id
        final modelId = model.toJson()['id']?.toString();
        if (modelId != null) {
          await _saveItemToCache(modelId, model);
        }
        await _invalidateListCache();
        await _queueSync('POST', baseEndpoint, model.toJson());
        return Result.success(model);
      }
      
      return Result.failure(ApiError(message: response.message ?? 'Failed to create'));
    } catch (e, stackTrace) {
      return Result.failure(NetworkError.fromException(e, stackTrace));
    }
  }

  /// Update - Returns Result<T> directly
  Future<Result<T>> update(String id, T model, {bool syncOffline = true}) async {
    try {
      final response = await apiService.put<Map<String, dynamic>>(
        '$baseEndpoint/$id',
        data: model.toJson(),
        fromJson: (data) => data as Map<String, dynamic>,
      );

      if (response.success && response.data != null) {
        final item = fromJson(response.data!);
        await _saveItemToCache(id, item);
        await _invalidateListCache();
        return Result.success(item);
      }

      // API failed - save locally for offline support
      if (syncOffline) {
        await _saveItemToCache(id, model);
        await _invalidateListCache();
        await _queueSync('PUT', '$baseEndpoint/$id', model.toJson());
        return Result.success(model);
      }
      
      return Result.failure(ApiError(message: response.message ?? 'Failed to update'));
    } catch (e, stackTrace) {
      return Result.failure(NetworkError.fromException(e, stackTrace));
    }
  }

  /// Delete - Returns Result<void> directly
  Future<Result<void>> delete(String id, {bool syncOffline = true}) async {
    try {
      final response = await apiService.delete<bool>('$baseEndpoint/$id');

      if (response.success) {
        await databaseService.delete(_itemCacheKey(id));
        await _invalidateListCache();
        return Result.success(null);
      }

      // API failed - delete locally for offline support
      if (syncOffline) {
        await databaseService.delete(_itemCacheKey(id));
        await _invalidateListCache();
        await _queueSync('DELETE', '$baseEndpoint/$id', null);
        return Result.success(null);
      }
      
      return Result.failure(ApiError(message: response.message ?? 'Failed to delete'));
    } catch (e, stackTrace) {
      return Result.failure(NetworkError.fromException(e, stackTrace));
    }
  }

  /// Toggle boolean field - Optimized version (accepts item directly)
  /// fieldName can be property name (isCompleted) or JSON key (completed)
  /// This is faster as it doesn't need to fetch the item first
  Future<Result<T>> toggleItem(T item, String fieldName, {bool syncOffline = true}) async {
    try {
      final itemJson = item.toJson();
      final id = itemJson['id']?.toString() ?? '';
      if (id.isEmpty) {
        return Result.failure(ValidationError(message: 'Item ID is required'));
      }
      
      // Find field key (try direct, then variations)
      String? jsonKey;
      for (final key in itemJson.keys) {
        if (key == fieldName || 
            key == fieldName.toLowerCase() ||
            key == fieldName.replaceFirst('is', '').toLowerCase()) {
          jsonKey = key;
          break;
        }
      }
      
      if (jsonKey == null || itemJson[jsonKey] is! bool) {
        return Result.failure(ValidationError(
          message: 'Field "$fieldName" not found or is not a boolean',
        ));
      }
      
      // Toggle the value
      final currentValue = itemJson[jsonKey] as bool;
      final updatedJson = {...itemJson, jsonKey: !currentValue};
      final updated = fromJson(updatedJson);
      
      // Save to database immediately (optimistic update)
      await _saveItemToCache(id, updated);
      await _invalidateListCache();
      
      // Sync with API in background (non-blocking)
      _syncUpdateInBackground(id, updated, syncOffline);
      
      return Result.success(updated);
    } catch (e, stackTrace) {
      return Result.failure(NetworkError.fromException(e, stackTrace));
    }
  }

  /// Background sync for update (non-blocking)
  Future<void> _syncUpdateInBackground(String id, T model, bool syncOffline) async {
    try {
      final response = await apiService.put<Map<String, dynamic>>(
        '$baseEndpoint/$id',
        data: model.toJson(),
        fromJson: (data) => data as Map<String, dynamic>,
      );

      if (response.success && response.data != null) {
        // Update cache with server response
        final item = fromJson(response.data!);
        await _saveItemToCache(id, item);
        await _invalidateListCache();
      } else if (syncOffline) {
        // Queue for later sync
        await _queueSync('PUT', '$baseEndpoint/$id', model.toJson());
      }
    } catch (e) {
      // If sync fails, queue for later
      if (syncOffline) {
        await _queueSync('PUT', '$baseEndpoint/$id', model.toJson());
      }
    }
  }

  /// Toggle by ID (slower, use toggleItem when you have the item)
  /// fieldName can be property name (isCompleted) or JSON key (completed)
  Future<Result<T>> toggle(String id, String fieldName, {bool syncOffline = true}) async {
    try {
      // Try cache first (for newly created items)
      T? item = _getCachedItem(id);
      if (item == null) {
        // Not in cache, try API
        final result = await getById(id, useCache: false);
        if (result.isFailure) return Result.failure(result.error!);
        item = result.value!;
      }
      
      // Use optimized toggleItem method
      return await toggleItem(item, fieldName, syncOffline: syncOffline);
    } catch (e, stackTrace) {
      return Result.failure(NetworkError.fromException(e, stackTrace));
    }
  }
}
